name: "Codecov test runner: main branch"

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test -- --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3