name: "Codecov runner: main branch"

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3