name: "Codecov runner: main branch"

on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3